### ISSUE TITLE
Is this thread safe ?

### ISSUE THREAD

**Issue by akhushnazarov** [MeVitae/redis-work-queue#10]
can i run workers in multiple threads ?

**Comment by JOT85** [comment]
Yep! You'll see, in each API, the methods take a redis client as an argument.

If each thread has it's own redis client, you can pass the different redis clients as arguments. 

Many of the redis clients are also thread safe, meaning you can share a client between threads.

Which language(s) are you using?

**Comment by akhushnazarov** [comment]
Sorry forgot to mention the language. I am using python.

**Comment by JOT85** [comment]
Yes, the methods on the `WorkQueue` class itself don't mutate the state of the class, and, according to [`redis-py > Advanced Features`](https://redis-py.readthedocs.io/en/stable/advanced_features.html), the redis client is also thread safe.
